/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package projfinal;

import java.awt.GridLayout;
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.KeyEvent;
import java.io.IOException;
import java.net.SocketTimeoutException;
import java.net.URL;
import java.util.ArrayList;
import javax.imageio.ImageIO;
import javax.sound.sampled.SourceDataLine;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.ScrollPaneConstants;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author sw4rtz
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSearch = new javax.swing.JButton();
        txtLink = new javax.swing.JTextField();
        flagDominios = new javax.swing.JCheckBox();
        level = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        btnIPT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Projeto");
        setBackground(new java.awt.Color(255, 255, 255));

        btnSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Assets/pesquisa.png"))); // NOI18N
        btnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtLink.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtLink.setText("Link");
        txtLink.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLinkKeyPressed(evt);
            }
        });

        flagDominios.setText("Dominios");

        level.setModel(new javax.swing.SpinnerNumberModel(1, 1, 9, 1));
        level.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel1.setText("Nivel");

        btnIPT.setText("IPT");
        btnIPT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIPTActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtLink)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(flagDominios, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnIPT)
                        .addGap(105, 105, 105)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(flagDominios, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(level, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIPT))
                .addGap(27, 27, 27)
                .addComponent(txtLink, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtLinkKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLinkKeyPressed
        if (evt.getKeyCode()== KeyEvent.VK_ENTER){
                btnSearchActionPerformed(evt);
        }// TODO add your handling code here:
    }//GEN-LAST:event_txtLinkKeyPressed

    private void btnIPTActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_btnIPTActionPerformed
        txtLink.setText("http://www.ipt.pt");
    }// GEN-LAST:event_btnIPTActionPerformed

    private void txtLinkActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_txtLinkActionPerformed
        // TODO add your handling code here:
    }// GEN-LAST:event_txtLinkActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) throws IOException {// GEN-FIRST:event_btnSearchActionPerformed
        String link = txtLink.getText();
        int nivel = (int) level.getValue();
        EDACrawler eda = new EDACrawler();
        Payload ini = eda.process(link, nivel);
        //int contaLinks = 0;
        //int contaImagens=0;

        //eda.process(link, nivel);

        /*
         * for(int i=1; i <= ini.links.size();i++){
         * auxi = eda.process(ini.links.get(i));
         * 
         * }
         */
        // EDACrawler eda = new EDACrawler(txtLink.getText(), level.getValue());
        int numberImgs = ini.imgs.size();
        int numberLinks = ini.links.size();
        String msg = "Foram encontradas " + numberImgs + " imagens em " + numberLinks + " links.";
        JOptionPane.showMessageDialog(this, msg);

        
        JPanel pane = new JPanel();
        
        JFrame f = new JFrame();
        
        JButton b1 = new JButton("1");
        JButton b2 = new JButton("1");
        JButton b3 = new JButton("1");
        JButton b4 = new JButton("1");
        JButton b5 = new JButton("1");
        JButton b6 = new JButton("1");
        JButton b7 = new JButton("1");
        JButton b8 = new JButton("1");
        JButton b9 = new JButton("1");

        /*f.add(b1);
        f.add(b2);
        f.add(b3);
        f.add(b4);
        f.add(b5);
        f.add(b6);
        f.add(b7);
        f.add(b8);
        f.add(b9);*/


        //GridLayout grid = (GridLayout)output.getLayout();
        //grid.setColumns(2);
        //grid.setRows(numberImgs/2);
        for (String img : ini.imgs) {
            try {
                Image image = null;
                URL url = new URL(img);
                image = ImageIO.read(url);
                JLabel lbl = new JLabel();
                ImageIcon icon = null;
                int iWidth = image.getWidth(null);
                int iHeight = image.getHeight(null);
                int newWidth = 100;
                if (iWidth > iHeight) {
                    icon = new ImageIcon(
                            image.getScaledInstance(newWidth, (newWidth * iHeight) / iWidth,
                                    Image.SCALE_DEFAULT));
                } else {
                    icon = new ImageIcon(
                            image.getScaledInstance((newWidth * iWidth) / iHeight, newWidth,
                                    Image.SCALE_DEFAULT));
                }
                lbl.setIcon(icon);
                f.add(lbl);
            } catch (IllegalArgumentException e) {
                System.out.println("Erro: " + img);
            }
        }
        
        //pane.setLayout(new GridLayout(ini.imgs.size()/4, 3, 20, 25));
        
            //JScrollPane scroll = new JScrollPane(pane,ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        //f.add(scroll);
        f.setLayout(new GridLayout(ini.imgs.size()/4, 3, 20, 25));
        f.setSize(1000, 500);
        f.setVisible(true);


        this.pack();

        // System.out.println(ini.imgs);
        // System.out.println(ini.links);

        /*
         * boolean teste = false;
         * // Coloca https:// no inicio do link caso o utilizador não o coloque
         * teste = link.contains("http://");
         * if (teste == false) {
         * teste = link.contains("https://");
         * if (teste == false) {
         * link = "https://" + link;
         * }
         * }
         */
        // EDACrawler eda = new EDACrawler();
        // Payload ini = eda.process(link);

        /*
         * String data1 = link;
         * String data2 = "teste";
         */
        // for(String str:ini.imgs){

        /*
         * URL url = new URL(str);
         * image = ImageIO.read(url);
         * 
         * ImageIcon icon = new ImageIcon(image);
         * 
         * }
         * 
         * Image image = null;
         * URL url = new URL("w.wallhaven.cc/full/pk/wallhaven-pkgkkp.png");
         * image = ImageIO.read(url);
         */
        /**
         * ****
         * ADICIONA DADOS À TABELA Object[] row = { data1, data2 };
         * DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
         *
         * model.addRow(row);
         */
        // System.out.println(ini.imgs);
    }// GEN-LAST:event_btnSearchActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIPT;
    private javax.swing.JButton btnSearch;
    private javax.swing.JCheckBox flagDominios;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JSpinner level;
    private javax.swing.JTextField txtLink;
    // End of variables declaration//GEN-END:variables
}
